version = 2
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runsc]
  runtime_type = "io.containerd.runsc.v1"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runsc.options]
    SystemdCgroup = true
    Rootless = false
    Runtime = "runsc"
    RuntimeArgs = ["--debug", "--debug-log=/var/log/runsc.log"]

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runsc-kvm]
  runtime_type = "io.containerd.runsc.v1"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runsc-kvm.options]
    SystemdCgroup = true
    Rootless = false
    Runtime = "runsc"
    RuntimeArgs = ["--debug", "--debug-log=/var/log/runsc.log", "--platform=ptrace"]

[plugins."io.containerd.grpc.v1.cri".cni]
  bin_dir = "/opt/cni/bin"
  conf_dir = "/etc/cni/net.d"